version: '3.9'

services:
  database:
    container_name: '${APP_NAME}-database'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - database_mysql:/var/lib/mysql
#      - ./docker/mysql:/var/lib/mysql

  php:
    container_name: '${APP_NAME}-php'
    build:
      context: docker/php
    ports:
      - '${PHP_PORT}:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: '${APP_NAME}-nginx'
    image: nginx:stable-alpine
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  database_mysql:
    driver: local